import { randomBytes } from 'crypto';
import { COURSE_GUEST_PARTITION } from './course-guest-policy';

export type CourseSessionState = 'created' | 'loading' | 'loaded' | 'failed' | 'blocked' | 'closed';
export type CourseSessionFailureCode = 'COURSE_GUEST_ATTACH_REJECTED' | 'COURSE_GUEST_ATTACH_TIMEOUT' | 'COURSE_NAVIGATION_BLOCKED' | 'COURSE_MAIN_FRAME_LOAD_FAILED' | 'COURSE_LOAD_TIMEOUT';

export interface CourseSessionSnapshot {
	sessionId: string;
	partition: string;
	navigationEpoch: number;
	state: CourseSessionState;
	failureCode?: CourseSessionFailureCode;
}

export interface CourseSessionNavigation {
	sessionId: string;
	partition: string;
	navigationEpoch: number;
}

export interface CourseSessionGuestLookup {
	sessionId: string;
	partition: string;
}

export interface CourseSessionRegistryOptions {
	/**
	 * 主进程销毁 guest 后可在这里清理该 session 的 Electron 存储或监听器。
	 * 会话在调用此回调前已经失效，因此回调不能重新授权旧的 guest。
	 */
	onClose?: (session: CourseSessionSnapshot) => void;
}

const SESSION_ID_BYTES = 32;
const SESSION_ID_PREFIX = 'course_';
export const COURSE_SESSION_PARTITION_PREFIX = `${COURSE_GUEST_PARTITION}-`;

/**
 * 主进程唯一的课程会话事实层。
 *
 * 渲染层提供的 sessionId / partition 只是待校验输入；只有本 registry 创建、
 * 未关闭且精确匹配的 pair 才能被未来的 will-attach-webview 处理器授权。
 */
export class CourseSessionRegistry {
	private readonly sessions = new Map<string, CourseSessionSnapshot>();
	private readonly onClose?: (session: CourseSessionSnapshot) => void;

	constructor(options: CourseSessionRegistryOptions = {}) {
		this.onClose = options.onClose;
	}

	create(): CourseSessionSnapshot {
		const sessionId = this.createSessionId();
		const session: CourseSessionSnapshot = {
			sessionId,
			partition: `${COURSE_SESSION_PARTITION_PREFIX}${sessionId}`,
			navigationEpoch: 0,
			state: 'created'
		};
		this.sessions.set(sessionId, session);
		return this.snapshot(session);
	}

	get(sessionId: string): CourseSessionSnapshot | undefined {
		const session = this.sessions.get(sessionId);
		return session && this.snapshot(session);
	}

	/** Starts a new main-frame navigation and invalidates all prior navigation events. */
	beginNavigation(sessionId: string): CourseSessionNavigation | undefined {
		const session = this.sessions.get(sessionId);
		if (!session || session.state === 'closed') return undefined;

		session.navigationEpoch += 1;
		session.state = 'loading';
		delete session.failureCode;
		return {
			sessionId: session.sessionId,
			partition: session.partition,
			navigationEpoch: session.navigationEpoch
		};
	}

	/** Returns false when the event belongs to a stale or already closed navigation. */
	markLoaded(sessionId: string, navigationEpoch: number): boolean {
		const session = this.sessions.get(sessionId);
		if (!session || session.state !== 'loading' || session.navigationEpoch !== navigationEpoch) return false;

		session.state = 'loaded';
		delete session.failureCode;
		return true;
	}

	/** Records a fixed, renderer-safe terminal loading outcome for the current navigation. */
	markTerminal(sessionId: string, navigationEpoch: number, state: Extract<CourseSessionState, 'failed' | 'blocked'>, failureCode: CourseSessionFailureCode): boolean {
		const session = this.sessions.get(sessionId);
		if (!session || session.state === 'closed' || session.navigationEpoch !== navigationEpoch || (session.state !== 'created' && session.state !== 'loading' && session.state !== 'loaded')) return false;

		session.state = state;
		session.failureCode = failureCode;
		return true;
	}

	/**
	 * Minimal future will-attach-webview query. It intentionally requires both facts;
	 * no caller can obtain authorization by supplying only a renderer-controlled id.
	 */
	findActiveGuest(lookup: CourseSessionGuestLookup): CourseSessionSnapshot | undefined {
		const session = this.sessions.get(lookup.sessionId);
		if (!session || session.state === 'closed' || session.partition !== lookup.partition) return undefined;
		return this.snapshot(session);
	}

	/**
	 * Electron only forwards a fixed set of standard <webview> attributes to
	 * will-attach-webview. In particular, renderer-owned data-* attributes are
	 * not an authorization transport. The partition below is generated by this
	 * registry, unique per course session, and can only be used while the main
	 * process has explicitly opened a loading epoch for it.
	 */
	findExpectedGuestByPartition(partition: string | undefined): CourseSessionSnapshot | undefined {
		if (typeof partition !== 'string') return undefined;
		for (const session of this.sessions.values()) {
			if (session.partition === partition && session.state === 'loading') return this.snapshot(session);
		}
		return undefined;
	}


	/**
	 * Invalidates the guest before invoking cleanup. Repeated close requests are no-ops,
	 * so cleanup is attempted exactly once for each created session.
	 */
	close(sessionId: string): boolean {
		const session = this.sessions.get(sessionId);
		if (!session || session.state === 'closed') return false;

		session.state = 'closed';
		session.navigationEpoch += 1;
		this.onClose?.(this.snapshot(session));
		return true;
	}

	/** Closes every active session when its owning main window is destroyed. */
	closeAll(): CourseSessionSnapshot[] {
		const closed: CourseSessionSnapshot[] = [];
		for (const session of Array.from(this.sessions.values())) {
			if (this.close(session.sessionId)) closed.push(this.snapshot(session));
		}
		return closed;
	}

	private createSessionId(): string {
		let sessionId: string;
		do {
			sessionId = `${SESSION_ID_PREFIX}${randomBytes(SESSION_ID_BYTES).toString('hex')}`;
		} while (this.sessions.has(sessionId));
		return sessionId;
	}

	private snapshot(session: CourseSessionSnapshot): CourseSessionSnapshot {
		return { ...session };
	}
}
